services:
  # Flask API 
  api:
    build: ./api
    container_name: web-api
    hostname: web-api
    volumes:
      - ./api:/apicode
    ports:
      - "4000:4000"  
    depends_on:
      - mysql_db
    environment:
      - DATABASE_URL=mysql+pymysql://user:password@mysql_db:3306/startupconnect 

  # Streamlit Frontend 
  app:
    build:
      context: ./app
      dockerfile: src/Dockerfile
    container_name: web-app
    hostname: web-app
    volumes:
      - ./app/src:/appcode
    ports:
      - "8502:8501"  
    depends_on:
      - api  

  # MySQL Database Service
  mysql_db:
    image: mysql:8  
    container_name: mysql_db
    hostname: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: startupsrule  
      MYSQL_DATABASE: StartUpConnect
      MYSQL_USER: user
      MYSQL_PASSWORD: password  
    volumes:
      - ./database-files:/docker-entrypoint-initdb.d/:ro
      - db_data:/var/lib/mysql  
    ports:
      - "3306:3306"  

volumes:
  db_data:





