USE StartUpConnect;

INSERT INTO CommunicationHistory (MessageID, MessageType, Timestamp, MessageContent) VALUES (1, 'Follow-up', '2023-07-04', 'When is the deadline for project submission?');
INSERT INTO CommunicationHistory (MessageID, MessageType, Timestamp, MessageContent) VALUES (2, 'Inquiry', '2023-02-05', 'When is the deadline for project submission?');
INSERT INTO CommunicationHistory (MessageID, MessageType, Timestamp, MessageContent) VALUES (3, 'Response', '2024-08-03', 'Your request has been escalated to our support team.');
INSERT INTO CommunicationHistory (MessageID, MessageType, Timestamp, MessageContent) VALUES (4, 'Follow-up', '2023-11-10', 'Your account settings were successfully updated.');
INSERT INTO CommunicationHistory (MessageID, MessageType, Timestamp, MessageContent) VALUES (5, 'Notification', '2024-03-01', 'Please let me know if you need additional information.');
INSERT INTO CommunicationHistory (MessageID, MessageType, Timestamp, MessageContent) VALUES (6, 'Response', '2023-08-22', 'Please let me know if you need additional information.');
INSERT INTO CommunicationHistory (MessageID, MessageType, Timestamp, MessageContent) VALUES (7, 'Follow-up', '2024-07-14', 'Please let me know if you need additional information.');
INSERT INTO CommunicationHistory (MessageID, MessageType, Timestamp, MessageContent) VALUES (8, 'Feedback', '2024-01-24', 'I need assistance with resetting my account password.');
INSERT INTO CommunicationHistory (MessageID, MessageType, Timestamp, MessageContent) VALUES (9, 'Feedback', '2024-01-06', 'The application works well, but the UI could use improvements.');
INSERT INTO CommunicationHistory (MessageID, MessageType, Timestamp, MessageContent) VALUES (10, 'Follow-up', '2024-05-31', 'Could you provide more details about the services offered?');
INSERT INTO CommunicationHistory (MessageID, MessageType, Timestamp, MessageContent) VALUES (11, 'Follow-up', '2023-05-26', 'Can we arrange a call to discuss the details?');
INSERT INTO CommunicationHistory (MessageID, MessageType, Timestamp, MessageContent) VALUES (12, 'Notification', '2024-09-15', 'Can we arrange a call to discuss the details?');
INSERT INTO CommunicationHistory (MessageID, MessageType, Timestamp, MessageContent) VALUES (13, 'Inquiry', '2024-08-14', 'Your feedback is much appreciated.');
INSERT INTO CommunicationHistory (MessageID, MessageType, Timestamp, MessageContent) VALUES (14, 'Inquiry', '2024-12-12', 'Could you provide more details about the services offered?');
INSERT INTO CommunicationHistory (MessageID, MessageType, Timestamp, MessageContent) VALUES (15, 'Notification', '2023-10-11', 'Let us know if theres anything else we can do for you.');
INSERT INTO CommunicationHistory (MessageID, MessageType, Timestamp, MessageContent) VALUES (16, 'Follow-up', '2024-05-25', 'A new version of the app is now available.');
INSERT INTO CommunicationHistory (MessageID, MessageType, Timestamp, MessageContent) VALUES (17, 'Feedback', '2024-02-27', 'Could you provide more details about the services offered?');
INSERT INTO CommunicationHistory (MessageID, MessageType, Timestamp, MessageContent) VALUES (18, 'Follow-up', '2023-01-18', 'We have received your request and will process it soon.');
INSERT INTO CommunicationHistory (MessageID, MessageType, Timestamp, MessageContent) VALUES (19, 'Inquiry', '2023-04-02', 'Thanks for the update. I will review and get back to you soon.');
INSERT INTO CommunicationHistory (MessageID, MessageType, Timestamp, MessageContent) VALUES (20, 'Feedback', '2023-01-13', 'The document you requested is attached.');
INSERT INTO CommunicationHistory (MessageID, MessageType, Timestamp, MessageContent) VALUES (21, 'Response', '2024-03-05', 'Could you provide more details about the services offered?');
INSERT INTO CommunicationHistory (MessageID, MessageType, Timestamp, MessageContent) VALUES (22, 'Feedback', '2024-10-11', 'When is the deadline for project submission?');
INSERT INTO CommunicationHistory (MessageID, MessageType, Timestamp, MessageContent) VALUES (23, 'Inquiry', '2023-06-12', 'The document you requested is attached.');
INSERT INTO CommunicationHistory (MessageID, MessageType, Timestamp, MessageContent) VALUES (24, 'Inquiry', '2024-06-19', 'Your feedback is much appreciated.');
INSERT INTO CommunicationHistory (MessageID, MessageType, Timestamp, MessageContent) VALUES (25, 'Response', '2023-03-25', 'Thank you for your patience.');
INSERT INTO CommunicationHistory (MessageID, MessageType, Timestamp, MessageContent) VALUES (26, 'Response', '2023-05-02', 'Your account settings were successfully updated.');
INSERT INTO CommunicationHistory (MessageID, MessageType, Timestamp, MessageContent) VALUES (27, 'Inquiry', '2023-05-30', 'Thank you for your patience.');
INSERT INTO CommunicationHistory (MessageID, MessageType, Timestamp, MessageContent) VALUES (28, 'Inquiry', '2023-01-16', 'The document you requested is attached.');
INSERT INTO CommunicationHistory (MessageID, MessageType, Timestamp, MessageContent) VALUES (29, 'Feedback', '2023-06-25', 'Can I schedule a meeting with your team next week?');
INSERT INTO CommunicationHistory (MessageID, MessageType, Timestamp, MessageContent) VALUES (30, 'Notification', '2023-12-29', 'A new version of the app is now available.');
INSERT INTO CommunicationHistory (MessageID, MessageType, Timestamp, MessageContent) VALUES (31, 'Follow-up', '2023-07-03', 'Can we arrange a call to discuss the details?');
INSERT INTO CommunicationHistory (MessageID, MessageType, Timestamp, MessageContent) VALUES (32, 'Follow-up', '2023-02-26', 'I need assistance with resetting my account password.');
INSERT INTO CommunicationHistory (MessageID, MessageType, Timestamp, MessageContent) VALUES (33, 'Notification', '2023-04-14', 'When is the deadline for project submission?');
INSERT INTO CommunicationHistory (MessageID, MessageType, Timestamp, MessageContent) VALUES (34, 'Inquiry', '2024-03-15', 'Thank you for your patience.');
INSERT INTO CommunicationHistory (MessageID, MessageType, Timestamp, MessageContent) VALUES (35, 'Response', '2023-04-30', 'Let us know if theres anything else we can do for you.');
INSERT INTO CommunicationHistory (MessageID, MessageType, Timestamp, MessageContent) VALUES (36, 'Notification', '2023-11-28', 'The application works well, but the UI could use improvements.');
INSERT INTO CommunicationHistory (MessageID, MessageType, Timestamp, MessageContent) VALUES (37, 'Notification', '2024-05-19', 'Your feedback is much appreciated.');
INSERT INTO CommunicationHistory (MessageID, MessageType, Timestamp, MessageContent) VALUES (38, 'Follow-up', '2023-10-11', 'Can you clarify the terms and conditions?');
INSERT INTO CommunicationHistory (MessageID, MessageType, Timestamp, MessageContent) VALUES (39, 'Inquiry', '2023-07-09', 'Thank you for your patience.');
INSERT INTO CommunicationHistory (MessageID, MessageType, Timestamp, MessageContent) VALUES (40, 'Follow-up', '2023-10-17', 'Could you provide more details about the services offered?');
INSERT INTO CommunicationHistory (MessageID, MessageType, Timestamp, MessageContent) VALUES (41, 'Response', '2023-04-11', 'Can we arrange a call to discuss the details?');
INSERT INTO CommunicationHistory (MessageID, MessageType, Timestamp, MessageContent) VALUES (42, 'Notification', '2024-01-18', 'Let us know if theres anything else we can do for you.');
INSERT INTO CommunicationHistory (MessageID, MessageType, Timestamp, MessageContent) VALUES (43, 'Inquiry', '2024-11-30', 'Let us know if theres anything else we can do for you.');
INSERT INTO CommunicationHistory (MessageID, MessageType, Timestamp, MessageContent) VALUES (44, 'Follow-up', '2023-11-07', 'What are the delivery options available for this product?');
INSERT INTO CommunicationHistory (MessageID, MessageType, Timestamp, MessageContent) VALUES (45, 'Follow-up', '2024-01-30', 'Thank you for your patience.');
INSERT INTO CommunicationHistory (MessageID, MessageType, Timestamp, MessageContent) VALUES (46, 'Inquiry', '2024-10-03', 'We have received your request and will process it soon.');
INSERT INTO CommunicationHistory (MessageID, MessageType, Timestamp, MessageContent) VALUES (47, 'Feedback', '2023-12-04', 'Your feedback is much appreciated.');
INSERT INTO CommunicationHistory (MessageID, MessageType, Timestamp, MessageContent) VALUES (48, 'Feedback', '2023-11-21', 'Please let me know if you need additional information.');
INSERT INTO CommunicationHistory (MessageID, MessageType, Timestamp, MessageContent) VALUES (49, 'Feedback', '2023-04-21', 'Could you provide more details about the services offered?');
INSERT INTO CommunicationHistory (MessageID, MessageType, Timestamp, MessageContent) VALUES (50, 'Inquiry', '2023-05-29', 'Your request has been escalated to our support team.');