USE StartUpConnect;

INSERT INTO Skills (SkillID, SkillName, SkillLevel) VALUES (1, 'Python Programming', 'Beginner');
INSERT INTO Skills (SkillID, SkillName, SkillLevel) VALUES (2, 'Data Analysis', 'Intermediate');
INSERT INTO Skills (SkillID, SkillName, SkillLevel) VALUES (3, 'Web Development', 'Beginner');
INSERT INTO Skills (SkillID, SkillName, SkillLevel) VALUES (4, 'Project Management', 'Beginner');
INSERT INTO Skills (SkillID, SkillName, SkillLevel) VALUES (5, 'Machine Learning', 'Beginner');
INSERT INTO Skills (SkillID, SkillName, SkillLevel) VALUES (6, 'Cloud Computing', 'Advanced');
INSERT INTO Skills (SkillID, SkillName, SkillLevel) VALUES (7, 'Database Management', 'Beginner');
INSERT INTO Skills (SkillID, SkillName, SkillLevel) VALUES (8, 'Cybersecurity', 'Advanced');
INSERT INTO Skills (SkillID, SkillName, SkillLevel) VALUES (9, 'Mobile App Development', 'Beginner');
INSERT INTO Skills (SkillID, SkillName, SkillLevel) VALUES (10, 'UI/UX Design', 'Beginner');
INSERT INTO Skills (SkillID, SkillName, SkillLevel) VALUES (11, 'SEO Optimization', 'Beginner');
INSERT INTO Skills (SkillID, SkillName, SkillLevel) VALUES (12, 'Social Media Marketing', 'Beginner');
INSERT INTO Skills (SkillID, SkillName, SkillLevel) VALUES (13, 'Blockchain Development', 'Intermediate');
INSERT INTO Skills (SkillID, SkillName, SkillLevel) VALUES (14, 'AI Model Training', 'Advanced');
INSERT INTO Skills (SkillID, SkillName, SkillLevel) VALUES (15, 'Graphic Design', 'Beginner');
INSERT INTO Skills (SkillID, SkillName, SkillLevel) VALUES (16, 'DevOps Practices', 'Advanced');
INSERT INTO Skills (SkillID, SkillName, SkillLevel) VALUES (17, 'Big Data Analysis', 'Intermediate');
INSERT INTO Skills (SkillID, SkillName, SkillLevel) VALUES (18, 'Natural Language Processing', 'Advanced');
INSERT INTO Skills (SkillID, SkillName, SkillLevel) VALUES (19, 'Software Testing', 'Beginner');
INSERT INTO Skills (SkillID, SkillName, SkillLevel) VALUES (20, 'Agile Methodologies', 'Advanced');
INSERT INTO Skills (SkillID, SkillName, SkillLevel) VALUES (21, 'Salesforce Administration', 'Beginner');
INSERT INTO Skills (SkillID, SkillName, SkillLevel) VALUES (22, 'Java Programming', 'Beginner');
INSERT INTO Skills (SkillID, SkillName, SkillLevel) VALUES (23, 'C++ Programming', 'Intermediate');
INSERT INTO Skills (SkillID, SkillName, SkillLevel) VALUES (24, 'Mobile UI Design', 'Intermediate');
INSERT INTO Skills (SkillID, SkillName, SkillLevel) VALUES (25, 'IT Support', 'Advanced');
INSERT INTO Skills (SkillID, SkillName, SkillLevel) VALUES (26, 'Network Engineering', 'Advanced');
INSERT INTO Skills (SkillID, SkillName, SkillLevel) VALUES (27, 'E-commerce Platforms', 'Intermediate');
INSERT INTO Skills (SkillID, SkillName, SkillLevel) VALUES (28, 'Robotics', 'Advanced');
INSERT INTO Skills (SkillID, SkillName, SkillLevel) VALUES (29, 'Embedded Systems', 'Advanced');
INSERT INTO Skills (SkillID, SkillName, SkillLevel) VALUES (30, 'Game Development', 'Beginner');
INSERT INTO Skills (SkillID, SkillName, SkillLevel) VALUES (31, 'System Administration', 'Intermediate');
INSERT INTO Skills (SkillID, SkillName, SkillLevel) VALUES (32, 'Cloud Architecture', 'Intermediate');
INSERT INTO Skills (SkillID, SkillName, SkillLevel) VALUES (33, 'Penetration Testing', 'Beginner');
INSERT INTO Skills (SkillID, SkillName, SkillLevel) VALUES (34, 'NoSQL Databases', 'Intermediate');
INSERT INTO Skills (SkillID, SkillName, SkillLevel) VALUES (35, 'AR/VR Development', 'Beginner');
INSERT INTO Skills (SkillID, SkillName, SkillLevel) VALUES (36, '3D Modeling', 'Intermediate');
INSERT INTO Skills (SkillID, SkillName, SkillLevel) VALUES (37, 'IoT Development', 'Intermediate');
INSERT INTO Skills (SkillID, SkillName, SkillLevel) VALUES (38, 'Digital Forensics', 'Beginner');
INSERT INTO Skills (SkillID, SkillName, SkillLevel) VALUES (39, 'Computer Vision', 'Intermediate');
INSERT INTO Skills (SkillID, SkillName, SkillLevel) VALUES (40, 'Data Visualization', 'Intermediate');
INSERT INTO Skills (SkillID, SkillName, SkillLevel) VALUES (41, 'Linux Administration', 'Intermediate');
INSERT INTO Skills (SkillID, SkillName, SkillLevel) VALUES (42, 'Docker & Kubernetes', 'Beginner');
INSERT INTO Skills (SkillID, SkillName, SkillLevel) VALUES (43, 'ITIL Framework', 'Advanced');
INSERT INTO Skills (SkillID, SkillName, SkillLevel) VALUES (44, 'Python Scripting', 'Intermediate');
INSERT INTO Skills (SkillID, SkillName, SkillLevel) VALUES (45, 'PowerShell', 'Intermediate');
INSERT INTO Skills (SkillID, SkillName, SkillLevel) VALUES (46, 'Data Engineering', 'Intermediate');
INSERT INTO Skills (SkillID, SkillName, SkillLevel) VALUES (47, 'API Development', 'Advanced');
INSERT INTO Skills (SkillID, SkillName, SkillLevel) VALUES (48, 'React Framework', 'Advanced');
INSERT INTO Skills (SkillID, SkillName, SkillLevel) VALUES (49, 'Angular Framework', 'Advanced');
INSERT INTO Skills (SkillID, SkillName, SkillLevel) VALUES (50, 'Terraform', 'Intermediate');